name: cafeit
description: "카페잇 - 내 주변의 분위기 좋은 카페, 함께 나누는 이야기"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ===== 인증 관련 =====
  # 소셜 로그인 (Firebase 없이)
  flutter_naver_login: ^1.1.0
  kakao_flutter_sdk: ^1.9.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  
  # ===== 위치 및 지도 =====
  # 위치 서비스
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # 네이버 지도 (웹뷰 방식)
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  
  # 위치 권한
  permission_handler: ^11.3.1

  # ===== 상태 관리 =====
  provider: ^6.1.2

  # ===== 데이터 저장 =====
  # 로컬 저장소
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ===== 네트워크 통신 =====
  dio: ^5.4.1
  http: ^1.2.0

  # ===== UI/UX =====
  # 이미지 처리
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  
  # 애니메이션
  lottie: ^3.1.2
  
  # 커스텀 위젯
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  
  # 폰트
  google_fonts: ^6.2.1

  # ===== 유틸리티 =====
  # 날짜/시간 처리
  intl: ^0.19.0
  
  # URL 처리
  url_launcher: ^6.2.5
  
  # 로깅
  logger: ^2.0.2+1
  
  # 앱 정보
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true